export const SUBDIRECCIONES_SEED: { name: string; description: string }[] = [
    { name: 'Oficina Asesora de Planeación', description: '' },
    { name: 'Subdirección de Salud Publica', description: '' },
    { name: 'Oficina Asesora Juridica', description: '' },
    { name: 'Subdirección de Calidad y Aseguramiento', description: '' },
    { name: 'Secretaria General', description: '' },
    { name: 'Control Interno de Gestión', description: '' },
    { name: 'Direccion', description: '' },
    { name: 'Control Interno Disciplinario', description: '' },
];

export const AREAS_SEED: { name: string; subdireccionName: string }[] = [
    { name: 'Sistemas de Informacion', subdireccionName: 'Oficina Asesora de Planeación' },
    { name: 'Proyectos', subdireccionName: 'Oficina Asesora de Planeación' },
    { name: 'Red de Servicios', subdireccionName: 'Oficina Asesora de Planeación' },
    { name: 'Calidad', subdireccionName: 'Oficina Asesora de Planeación' },
    { name: 'Oficina Direccion', subdireccionName: 'Direccion' },
    { name: 'Salud Infantil: Prmera infancia, infancia y adolescentes', subdireccionName: 'Oficina Asesora de Planeación' },
    { name: 'Salud Ambiental', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Sexualidad, derechos sexuales y reproductivos', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Salud Oral', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Vida saludable y enfermedades transmisibles ', subdireccionName: 'Subdirección de Salud Publica' },
    { name: ' Salud y ámbito laboral', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Contratacion', subdireccionName: 'Oficina Asesora Juridica' },
    { name: 'Tutelas', subdireccionName: 'Oficina Asesora Juridica' },
    { name: 'Habilitacion', subdireccionName: 'Subdirección de Calidad y Aseguramiento' },
    { name: 'Atencion al usuario', subdireccionName: 'Subdirección de Calidad y Aseguramiento' },
    { name: 'Contabilidad', subdireccionName: 'Secretaria General' },
    { name: 'Presupuesto', subdireccionName: 'Secretaria General' },
    { name: 'Tesoreria', subdireccionName: 'Secretaria General' },
    { name: 'OCIG', subdireccionName: 'Control Interno de Gestión' },
    { name: 'OCID', subdireccionName: 'Control Interno Disciplinario' },
    { name: 'Convivencia social  y salud mental', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Seguridad alimentaria y nutricional', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Laboratorio de Salud Pública', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Vigilancia en Salud Pública', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Movilización', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Gestión de conocimiento', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Enfermedades Transmitidas por Vectores -ETV-', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Salud pública en emergencias y desastres', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Envejecimiento y vejez', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Salud y género', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Asuntos etnicos', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Discapacidad', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Víctimas del conflicto', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Modelo Integral de atencion', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Comunicaciones en salud', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Plan Territorial de Salud', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Control de Medicamentos', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Vida Saludable y condiciones no transmisibles', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Subdireccion de salud pública', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'DLS', subdireccionName: 'Subdirección de Calidad y Aseguramiento' },
    { name: 'Aseguramiento', subdireccionName: 'Subdirección de Calidad y Aseguramiento' },
    { name: 'Cuentas Medicas', subdireccionName: 'Subdirección de Calidad y Aseguramiento' },
    { name: 'CRUE', subdireccionName: 'Subdirección de Calidad y Aseguramiento' },
    { name: 'Registro de Profesionales', subdireccionName: 'Subdirección de Calidad y Aseguramiento' },
    { name: 'Procesos Admin. Sancionatorios', subdireccionName: 'Subdirección de Calidad y Aseguramiento' },
    { name: 'IVC', subdireccionName: 'Subdirección de Calidad y Aseguramiento' },
    { name: 'Gestión Intervenciones Colectivas', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Talento Humano', subdireccionName: 'Secretaria General' },
    { name: 'Cancer', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Participacion Social', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Programa Ampliado de Inmunizaciones (PAI)', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Habitante de calle', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'GAUDI', subdireccionName: 'Subdirección de Calidad y Aseguramiento' },
    { name: 'Infraestructura', subdireccionName: 'Oficina Asesora de Planeación' },
    { name: 'Atención primaria en salud (APS)', subdireccionName: 'Subdirección de Salud Publica' },
    { name: 'Almacen', subdireccionName: 'Secretaria General' },
    { name: 'Apoyo Logistico', subdireccionName: 'Secretaria General' },
    { name: 'Gestión Documental', subdireccionName: 'Secretaria General' },
    { name: 'Seguridad y salud en el trabajo', subdireccionName: 'Secretaria General' },
];

export const MUNICIPIOS_SEED: { name: string; code: string | null }[] = [
    { name: 'ALBAN', code: '52019' },
    { name: 'ALDANA', code: '52022' },
    { name: 'ANCUYA', code: '52036' },
    { name: 'ARBOLEDA', code: '52051' },
    { name: 'BARBACOAS', code: '52079' },
    { name: 'BELEN', code: '52083' },
    { name: 'BUESACO', code: '52110' },
    { name: 'CHACHAGUI', code: '52240' },
    { name: 'COLON', code: '52203' },
    { name: 'CONSACA', code: '52207' },
    { name: 'CONTADERO', code: '52210' },
    { name: 'CORDOBA', code: '52215' },
    { name: 'CUASPUD', code: '52224' },
    { name: 'CUMBAL', code: '52227' },
    { name: 'CUMBITARA', code: '52233' },
    { name: 'EL CHARCO', code: '52250' },
    { name: 'EL PEÑOL', code: '52254' },
    { name: 'EL ROSARIO', code: '52256' },
    { name: 'EL TABLON DE GOMEZ', code: '52258' },
    { name: 'EL TAMBO', code: '52260' },
    { name: 'FRANCISCO PIZARRO', code: '52520' },
    { name: 'FUNES', code: '52287' },
    { name: 'GUACHUCAL', code: '52317' },
    { name: 'GUAITARILLA', code: '52320' },
    { name: 'GUALMATAN', code: '52323' },
    { name: 'ILES', code: '52352' },
    { name: 'IMUES', code: '52354' },
    { name: 'IPIALES', code: '52356' },
    { name: 'LA CRUZ', code: '52378' },
    { name: 'LA FLORIDA', code: '52381' },
    { name: 'LA LLANADA', code: '52385' },
    { name: 'LA TOLA', code: '52390' },
    { name: 'LA UNION', code: '52399' },
    { name: 'LEIVA', code: '52405' },
    { name: 'LINARES', code: '52411' },
    { name: 'LOS ANDES', code: '52418' },
    { name: 'MAGUI', code: '52427' },
    { name: 'MALLAMA', code: '52435' },
    { name: 'MOSQUERA', code: '52473' },
    { name: 'NARIÑO', code: '52480' },
    { name: 'OLAYA HERRERA', code: '52490' },
    { name: 'OSPINA', code: '52506' },
    { name: 'PASTO', code: '52001' },
    { name: 'POLICARPA', code: '52540' },
    { name: 'POTOSI', code: '52560' },
    { name: 'PROVIDENCIA', code: '52565' },
    { name: 'PUERRES', code: '52573' },
    { name: 'PUPIALES', code: '52585' },
    { name: 'RICAURTE', code: '52612' },
    { name: 'ROBERTO PAYAN', code: '52621' },
    { name: 'SAMANIEGO', code: '52678' },
    { name: 'SAN BERNARDO', code: '52685' },
    { name: 'SAN LORENZO', code: '52687' },
    { name: 'SAN PABLO', code: '52693' },
    { name: 'SAN PEDRO DE CARTAGO', code: '52694' },
    { name: 'SANDONA', code: '52683' },
    { name: 'SANTA BARBARA', code: '52696' },
    { name: 'SANTACRUZ', code: '52699' },
    { name: 'SAPUYES', code: '52720' },
    { name: 'TAMINANGO', code: '52786' },
    { name: 'TANGUA', code: '52788' },
    { name: 'TUMACO', code: '52835' },
    { name: 'TUQUERRES', code: '52838' },
    { name: 'YACUANQUER', code: '52885' },
];

export const ENTIDADES_SEED: string[] = [
    'DLS/Secretario de Salud',
    'Coord. Salud Publica',
    'Coord. Aseguramiento',
    'Técnico de Saneamiento',
    'Financiero',
    'Coord. Gestion del Riesgo',
    'Alcalde',
    'Referente PIC',
];

export const IPS_TIPOS_SEED: string[] = [
    'Publicas',
    'Privadas',
    'Indigenas',
    'Regimen Excepcion',
    'Regimen Especial',
];

export const IPS_ACTORES_SEED: string[] = [
    'Gerente o delegado',
    'Médico',
    'Enfermero',
    'Psicologo',
    'Odontologo',
    'Bacteriologo',
    'Coord. PYP',
    'Coord. SP',
    'Tecnico Sivigila',
    'Responsable PAI',
    'Regente Farmacia',
    'Quim. Farmaceutico',
    'Coord./lider SGSST',
    'Ref. Afiliación',
    'Coord. Cartera',
    'Coord. Facturación',
    'Coord. Aten. Usuario',
    'Ref. PIC',
    'Cor. Seg Paciente',
];

export const EAPB_SEED: string[] = [
    'Emssanar',
    'Asmet Salud',
    'Sanitas',
    'Nueva EPS',
];

export const EAPB_ACTORES_SEED: string[] = [
    'Gerente o delegado',
    'Gestor Municipal',
    'Coord. de Vigilancia SP',
];

export const ORGANIZACIONES_SEED: string[] = [
    'Etnicas',
    'Academia',
    'Estable. Farmaceuticos',
    'Sociales Y comunitarias',
    'Lab. Clinico Privados',
    'Registraduria-Notarias',
    'Personeria',
    'Comites',
    'ARL',
    'Estable. objeto de Vigilancia',
];

export const IDSN_SEED: string[] = [
    'Auxiliar en salud',
];
